// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: getfeedidbyurl.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getFeedIdByUrl = `-- name: GetFeedIdByUrl :one
SELECT id FROM feeds WHERE url = $1
`

func (q *Queries) GetFeedIdByUrl(ctx context.Context, url string) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, getFeedIdByUrl, url)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
