// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: resetfeedstofetch.sql

package database

import (
	"context"
)

const resetFeedsToFetch = `-- name: ResetFeedsToFetch :exec
UPDATE feeds
    SET last_fetched_at = NULL
WHERE last_fetched_at IS NOT NULL
`

func (q *Queries) ResetFeedsToFetch(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetFeedsToFetch)
	return err
}
