// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: unfollowfeedfollow.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const unfollowFeedFollow = `-- name: UnfollowFeedFollow :exec
DELETE FROM feed_follows WHERE user_id = $1 AND feed_id = $2
`

type UnfollowFeedFollowParams struct {
	UserID uuid.UUID
	FeedID uuid.UUID
}

func (q *Queries) UnfollowFeedFollow(ctx context.Context, arg UnfollowFeedFollowParams) error {
	_, err := q.db.ExecContext(ctx, unfollowFeedFollow, arg.UserID, arg.FeedID)
	return err
}
